/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantalla;

/**
 *
 * @author Estudiante
 */
public class Mkicalcualdora extends javax.swing.JFrame {
     boolean sumando = false;
    boolean restando = false;
    boolean multiplicacion = false;
    boolean dividiendo = false;
    public double numero1;

    public Mkicalcualdora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        TxtNUM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LblMULTIPLICACION = new javax.swing.JLabel();
        LblIgual = new javax.swing.JLabel();
        lblMENOS = new javax.swing.JLabel();
        LblDIVISION = new javax.swing.JLabel();
        LblMAS = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 212, 182));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 50, 50));

        TxtNUM.setText("0");
        TxtNUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNUMActionPerformed(evt);
            }
        });
        jPanel1.add(TxtNUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 280, 30));

        jLabel4.setText("Calculadora");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 210, 40));
        jLabel4.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Estudiante\\Desktop\\topbar.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 735, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Estudiante\\Desktop\\Text field (1).png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 179, 357, -1));

        LblMULTIPLICACION.setIcon(new javax.swing.ImageIcon("C:\\Users\\Estudiante\\Desktop\\Small FAB (1).png")); // NOI18N
        LblMULTIPLICACION.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblMULTIPLICACIONMouseClicked(evt);
            }
        });
        jPanel1.add(LblMULTIPLICACION, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 284, -1, -1));

        LblIgual.setIcon(new javax.swing.ImageIcon("C:\\Users\\Estudiante\\Desktop\\Small FAB.png")); // NOI18N
        LblIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblIgualMouseClicked(evt);
            }
        });
        jPanel1.add(LblIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 284, -1, -1));

        lblMENOS.setIcon(new javax.swing.ImageIcon("C:\\Users\\Estudiante\\Desktop\\FAB (2).png")); // NOI18N
        lblMENOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMENOSMouseClicked(evt);
            }
        });
        jPanel1.add(lblMENOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 284, -1, -1));

        LblDIVISION.setIcon(new javax.swing.ImageIcon("C:\\Users\\Estudiante\\Desktop\\FAB (1).png")); // NOI18N
        LblDIVISION.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblDIVISIONMouseClicked(evt);
            }
        });
        jPanel1.add(LblDIVISION, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 292, -1, -1));

        LblMAS.setIcon(new javax.swing.ImageIcon("C:\\Users\\Estudiante\\Desktop\\dcfas.png")); // NOI18N
        LblMAS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblMASMouseClicked(evt);
            }
        });
        jPanel1.add(LblMAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 284, -1, -1));

        jButton2.setText("ac");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LblMASMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblMASMouseClicked
       sumando = true; 
        numero1 = operaciones.PrimerNroyBorrar(TxtNUM);
    }//GEN-LAST:event_LblMASMouseClicked

    private void lblMENOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMENOSMouseClicked
        restando = true; 
        numero1 = operaciones.PrimerNroyBorrar(TxtNUM);
    }//GEN-LAST:event_lblMENOSMouseClicked

    private void LblMULTIPLICACIONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblMULTIPLICACIONMouseClicked
        multiplicacion = true; 
       numero1 = operaciones.PrimerNroyBorrar(TxtNUM);
    }//GEN-LAST:event_LblMULTIPLICACIONMouseClicked

    private void LblDIVISIONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblDIVISIONMouseClicked
        dividiendo = true; 
       numero1 = operaciones.PrimerNroyBorrar(TxtNUM);
    }//GEN-LAST:event_LblDIVISIONMouseClicked

    private void LblIgualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblIgualMouseClicked
        double resultado = operaciones.calcular(numero1, TxtNUM, this);
    TxtNUM.setText(resultado + "");

    }//GEN-LAST:event_LblIgualMouseClicked

    private void TxtNUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNUMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNUMActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        operaciones.limpiarCalculadora(TxtNUM, this);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mkicalcualdora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mkicalcualdora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mkicalcualdora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mkicalcualdora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mkicalcualdora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblDIVISION;
    private javax.swing.JLabel LblIgual;
    private javax.swing.JLabel LblMAS;
    private javax.swing.JLabel LblMULTIPLICACION;
    private javax.swing.JTextField TxtNUM;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMENOS;
    // End of variables declaration//GEN-END:variables
}
